### ISSUE TITLE
Error regarding invalid signature

### ISSUE THREAD

**Issue by LIU-TIANHANG** [lauweijie/passport-nus-openid#1]
Good day,
                when I try to implemented this in express (4.16.4). I faced a err  as below
InternalOpenIDError: Failed to verify assertion
    at C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\passport-openid\lib\passport-openid\strategy.js:184:36
    at C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:1068:12
    at C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:1192:16
    at C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:1276:7
    at Object.openid.loadAssociation (C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:107:5)
    at _checkSignatureUsingAssociation (C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:1238:10)
    at _checkSignature (C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:1228:5)
    at _verifyAssertionAgainstProviders (C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:1188:12)
    at C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:1153:7
    at C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:686:7
    at _parseHtml (C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:489:5)
    at _resolveHtml (C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:589:5)
    at C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:556:16
    at done (C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:258:9)
    at IncomingMessage.<anonymous> (C:\Users\tainh\Desktop\github\Oauth-testing\node_modules\openid\openid.js:262:32)
    at emitNone (events.js:111:20)

when I attach an error handling is shows :
  name: 'InternalOpenIDError',
  message: 'Failed to verify assertion',
  openidError: { message: 'Invalid signature' } }

is there any way to solve this problem?

**Comment by gabrielchao** [comment]
I was having the same error and was able to resolve it by switching from passport and passport-openid to [@passport-next/passport](https://www.npmjs.com/package/@passport-next/passport) and [@passport-next/passport-openid](https://www.npmjs.com/package/@passport-next/passport-openid).

**Comment by DivineDX** [comment]
> I was having the same error and was able to resolve it by switching from passport and passport-openid to [@passport-next/passport](https://www.npmjs.com/package/@passport-next/passport) and [@passport-next/passport-openid](https://www.npmjs.com/package/@passport-next/passport-openid).

Hi, are you able to show a sample demo of your node.js app which works? I'm tried what you said but still encountered the same problem as OP above. Greatly appreciate it!

**Comment by pratyayj** [comment]
Hi! May I know the code that you used to get this to work in the end? I'm still rather confused with regards to Passportjs. Thank you very much for your help!

**Comment by gabrielchao** [comment]
Sorry for the very long delay. I ended up partially rewriting the file instead of importing it. Below is the `passport-setup.js` I used: 

```javascript
const OpenIdStrategy = require("@passport-next/passport-openid").Strategy;
const pgp = require('pg-promise');

const util = require("util");
const User = require("../models/User");

function makeEnvURL(url) {
  if(process.env.NODE_ENV === "production") return process.env.ROOT_URL + url;
  return "http://localhost:5000" + url;
}

function NusStrategy(options, validate) {
  options = options || {};
  options.providerURL = options.providerURL || "https://openid.nus.edu.sg/";
  options.profile = options.profile === undefined ? true : options.profile;

  OpenIdStrategy.call(this, options, validate);
  this.name = "nus-openid";
}

util.inherits(NusStrategy, OpenIdStrategy);

module.exports = passport => {
  // Tell passport how to serialize the user so session can be stored via cookie
  passport.serializeUser((user, done) => {
    done(null, user.user_id); // Use user_id to uniquely identify the user
  });

  passport.deserializeUser(async (user_id, done) => {
    try {
      const user = await User.findByUserID(user_id);
      // Sucessfully retrieved user
      // Now return it to passport to maintain the session
      done(null, user);
    } catch (err) {
      done(err, false); // Database error
    }
  });

  passport.use(
    new NusStrategy(
      {
        returnURL: makeEnvURL("/auth/nus/return"),
        realm: makeEnvURL("/"),
        profile: true
      },
      async (identifier, profile, done) => {
        console.log(`Verifying. Received profile ${profile}`);

        try {
          try {
            const user = await User.findByNusnetID(identifier);
            console.log(`Authenticated user ${user.fullname}`);
            return done(null, user); // User exists. Attach it to passport
          }
          catch(err) {
            if(err.code === pgp.errors.queryResultErrorCode.noData) {
              // User does not exist in database yet.
              user = {
                nusnet_id: identifier,
                fullname: profile.displayName,
                email: profile.emails === [] ? null : profile.emails[0].value
              };
              user = await User.insert(user);
              return done(null, user, {
                message: `Registered new NUSNET ID ${user.nusnet_id}`
              });
            }
            else {
              throw err;
            }
          }
        } catch (err) {
          console.error("Error accessing database!");
          console.error(err);
          return done(err); // Database exception
        }
      }
    )
  );
};
```
